"""Run HNSW/IVFFlat parameter sensitivity experiments.

Each condition invokes the complete repeated calibration/held-out harness.
The reported strategy for HNSW conditions is ``HNSW_HYBRID``; the reported
strategy for IVFFlat conditions is ``IVFFLAT_HYBRID``. The output also retains
the across-run confidence intervals generated by the harness.

Example:
    venv/bin/python -m sdao.db.sensitivity_analysis \
        --output sdao/results/db_sensitivity_20260820
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from .evaluate_heldout import DEFAULT_BOOTSTRAPS, DEFAULT_CALIBRATION_FRACTION, DEFAULT_CALIBRATION_REPETITIONS
from .evaluate_heldout import DEFAULT_QUERY_COUNT, DEFAULT_REPETITIONS, run


HNSW_VALUES = (40, 100, 200, 400)
IVFFLAT_VALUES = (1, 5, 10, 20)
TARGET_RECALL = 0.95


def condition_args(args: argparse.Namespace, condition_output: Path,
                   index_type: str, value: int) -> argparse.Namespace:
    return argparse.Namespace(
        output=condition_output,
        query_count=args.query_count,
        calibration_fraction=args.calibration_fraction,
        calibration_repetitions=args.calibration_repetitions,
        repetitions=args.repetitions,
        top_k=args.top_k,
        safety_factor=args.safety_factor,
        seed=args.seed,
        bootstrap_samples=args.bootstrap_samples,
        runs=args.runs,
        hnsw_ef_search=value if index_type == "HNSW" else args.baseline_hnsw_ef_search,
        ivfflat_probes=value if index_type == "IVFFLAT" else args.baseline_ivfflat_probes,
    )


def write_latex_table(frame: pd.DataFrame, path: Path) -> None:
    columns = [
        "index_type", "parameter_value", "strategy", "mean_latency_ms",
        "latency_ci95_low_ms", "latency_ci95_high_ms", "mean_recall_at_10",
        "recall_ci95_low", "recall_ci95_high",
    ]
    table = frame[columns].rename(columns={
        "index_type": "Index", "parameter_value": "Parameter", "strategy": "Strategy",
        "mean_latency_ms": "Mean latency ms", "latency_ci95_low_ms": "Latency CI low",
        "latency_ci95_high_ms": "Latency CI high", "mean_recall_at_10": "Mean Recall@10",
        "recall_ci95_low": "Recall CI low", "recall_ci95_high": "Recall CI high",
    })
    path.write_text(
        table.to_latex(index=False, float_format="%.4f", caption=(
            "HNSW ef\\_search and IVFFlat probes sensitivity on repeated held-out evaluations. "
            "Intervals are bootstrap 95\\% CIs across run-level means."
        ), label="tab:ann-sensitivity", escape=True) + "\n",
        encoding="utf-8",
    )


def write_plot(frame: pd.DataFrame, path: Path) -> None:
    figure, axes = plt.subplots(1, 2, figsize=(8.0, 3.5), sharey=True)
    for axis, index_type, parameter_label, color in (
        (axes[0], "HNSW", "HNSW ef_search", "#0072B2"),
        (axes[1], "IVFFLAT", "IVFFlat probes", "#D55E00"),
    ):
        subset = frame[frame["index_type"] == index_type].sort_values("parameter_value")
        axis.plot(subset["parameter_value"], subset["mean_recall_at_10"], marker="o", color=color)
        axis.fill_between(
            subset["parameter_value"], subset["recall_ci95_low"], subset["recall_ci95_high"],
            color=color, alpha=0.15,
        )
        axis.axhline(TARGET_RECALL, color="black", linestyle="--", linewidth=0.9)
        axis.set_xlabel(parameter_label)
        axis.set_ylim(0, 1.05)
        axis.grid(True, color="0.88", linewidth=0.6)
    axes[0].set_ylabel("Recall@10")
    axes[1].text(0.98, 0.04, "Dashed line: target = 0.95", transform=axes[1].transAxes,
                 ha="right", va="bottom", fontsize=8)
    figure.tight_layout()
    figure.savefig(path, format="pdf", bbox_inches="tight")
    plt.close(figure)


def run_sensitivity(args: argparse.Namespace) -> pd.DataFrame:
    if args.output.exists() and any(args.output.iterdir()):
        raise FileExistsError(f"output directory is not empty: {args.output}")
    args.output.mkdir(parents=True, exist_ok=True)
    rows = []
    conditions = [("HNSW", value, "HNSW_HYBRID") for value in HNSW_VALUES]
    conditions += [("IVFFLAT", value, "IVFFLAT_HYBRID") for value in IVFFLAT_VALUES]
    for index_type, value, strategy in conditions:
        condition_output = args.output / f"{index_type.lower()}_{value}"
        run(condition_args(args, condition_output, index_type, value))
        summary = pd.read_csv(condition_output / "repeated_summary.csv")
        selected = summary[summary["strategy"] == strategy]
        if len(selected) != 1:
            raise RuntimeError(f"missing {strategy} summary for {index_type}={value}")
        row = selected.iloc[0].to_dict()
        rows.append({
            "index_type": index_type,
            "parameter_value": value,
            "strategy": strategy,
            **row,
        })
    frame = pd.DataFrame(rows)
    frame.to_csv(args.output / "sensitivity_summary.csv", index=False)
    write_latex_table(frame, args.output / "sensitivity_summary.tex")
    write_plot(frame, args.output / "figure_sensitivity_recall.pdf")
    return frame


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--query-count", type=int, default=DEFAULT_QUERY_COUNT)
    parser.add_argument("--calibration-fraction", type=float, default=DEFAULT_CALIBRATION_FRACTION)
    parser.add_argument("--calibration-repetitions", type=int, default=DEFAULT_CALIBRATION_REPETITIONS)
    parser.add_argument("--repetitions", type=int, default=DEFAULT_REPETITIONS)
    parser.add_argument("--runs", type=int, default=5)
    parser.add_argument("--top-k", type=int, default=10)
    parser.add_argument("--safety-factor", type=float, default=2.0)
    parser.add_argument("--seed", type=int, default=20260820)
    parser.add_argument("--bootstrap-samples", type=int, default=DEFAULT_BOOTSTRAPS)
    parser.add_argument("--baseline-hnsw-ef-search", type=int, default=100)
    parser.add_argument("--baseline-ivfflat-probes", type=int, default=10)
    return parser


def main() -> None:
    args = build_parser().parse_args()
    if args.runs < 2 or args.bootstrap_samples < 100:
        raise SystemExit("runs must be at least 2 and bootstrap-samples must be at least 100")
    frame = run_sensitivity(args)
    print(frame[["index_type", "parameter_value", "strategy", "mean_latency_ms", "mean_recall_at_10"]].to_string(index=False))
    print(f"Wrote sensitivity artifacts to {args.output}")


if __name__ == "__main__":
    main()